export const curatedIncidents = [
  // === REDIS ===
  {
    title: 'Redis Connection Refused',
    service: 'submission-service',
    severity: 'high',
    category: 'database',
    logs: ['Error: connect ECONNREFUSED redis:6379', 'RedisError: Connection lost', 'Retrying connection... attempt 5/5', 'Fatal: Could not connect to Redis after 5 retries'],
    rootCause: 'Redis container stopped or crashed, connection refused on port 6379',
    suggestedFix: '1. Run `docker ps` to check if Redis container is running\n2. Restart with `docker restart redis`\n3. Check Redis logs: `docker logs redis`\n4. Verify REDIS_URL env var points to correct host',
  },
  {
    title: 'Redis OOM — Out of Memory',
    service: 'cache-service',
    severity: 'critical',
    category: 'database',
    logs: ['MISCONF Redis is configured to save RDB snapshots', 'OOM command not allowed when used memory > maxmemory', 'ERR max number of clients reached', 'WARNING: Redis memory usage at 98%'],
    rootCause: 'Redis maxmemory limit reached, eviction policy not configured for cache workload',
    suggestedFix: '1. Set `maxmemory-policy allkeys-lru` in redis.conf\n2. Increase maxmemory or add more nodes\n3. Audit large keys: `redis-cli --bigkeys`\n4. Enable keyspace notifications to track expiry',
  },
  {
    title: 'Redis Cluster Node Failover',
    service: 'session-service',
    severity: 'high',
    category: 'database',
    logs: ['CLUSTERDOWN The cluster is down', 'MOVED 7638 redis-node-2:6379', 'Cluster node redis-node-1 unreachable', 'Failover election started for slot 0-5460'],
    rootCause: 'Redis cluster primary node for slots 0-5460 went offline triggering automatic failover',
    suggestedFix: '1. Check cluster status: `redis-cli cluster info`\n2. Identify failed nodes: `redis-cli cluster nodes`\n3. Allow failover to complete (typically 10-30s)\n4. Restart failed node and rejoin cluster',
  },
  {
    title: 'Redis Auth Failure',
    service: 'api-gateway',
    severity: 'medium',
    category: 'database',
    logs: ['NOAUTH Authentication required', 'Error: Redis authentication failed', 'Connection rejected — invalid password', 'Failed to authenticate with Redis server'],
    rootCause: 'REDIS_PASSWORD env var missing or incorrect after Redis restart with auth enabled',
    suggestedFix: '1. Verify REDIS_PASSWORD env var is set correctly\n2. Test manually: `redis-cli -a $REDIS_PASSWORD ping`\n3. Check Redis requirepass config\n4. Rotate password if compromised',
  },
  {
    title: 'Redis Pub/Sub Disconnected',
    service: 'realtime-service',
    severity: 'medium',
    category: 'realtime',
    logs: ['Redis subscriber disconnected', 'Lost subscription to channel: room:updates', 'Reconnection attempt failed', 'Message queue backing up — 1200 pending messages'],
    rootCause: 'Network interruption broke the Redis pub/sub subscriber connection, messages accumulated',
    suggestedFix: '1. Enable auto-reconnect in Redis client config\n2. Implement message buffering during reconnection\n3. Add health check for subscriber connection\n4. Consider Redis Streams for durability',
  },

  // === MONGODB ===
  {
    title: 'MongoDB Connection Timeout',
    service: 'user-service',
    severity: 'high',
    category: 'database',
    logs: ['MongoTimeoutError: Server selection timed out after 30000ms', 'No servers available matching ReadPreference', 'connection closed', 'MongoNetworkError: connection timed out'],
    rootCause: 'MongoDB Atlas cluster paused due to inactivity (free tier) or network ACL blocking backend IP',
    suggestedFix: '1. Check Atlas cluster status — resume if paused\n2. Verify IP whitelist includes server IP\n3. Check MONGODB_URI connection string\n4. Add retryWrites=true&retryReads=true to connection string',
  },
  {
    title: 'MongoDB Duplicate Key Error',
    service: 'auth-service',
    severity: 'medium',
    category: 'database',
    logs: ['MongoServerError: E11000 duplicate key error collection: users index: email_1', 'WriteError: duplicate key error on field: email', 'Document insertion failed for user registration'],
    rootCause: 'Race condition — two concurrent registration requests with same email passed validation simultaneously',
    suggestedFix: '1. Handle E11000 error gracefully with 409 Conflict response\n2. Add try-catch around upsert operations\n3. Consider optimistic locking for concurrent writes\n4. Email uniqueness constraint is working correctly — handle in application layer',
  },
  {
    title: 'MongoDB Atlas Index Build Blocking Writes',
    service: 'problem-service',
    severity: 'medium',
    category: 'database',
    logs: ['Write blocked waiting for index build', 'IndexBuildAborted: Index build interrupted', 'Slow query detected: 12400ms on collection problems', 'Collection scan with no index on field: tags'],
    rootCause: 'Foreground index build on large collection blocked write operations during deployment',
    suggestedFix: '1. Always use background index builds: `createIndex({}, {background: true})`\n2. Build indexes during low-traffic windows\n3. Add missing index on `tags` field\n4. Monitor with `db.currentOp({op: "command"})`',
  },
  {
    title: 'MongoDB Transaction Aborted',
    service: 'submission-service',
    severity: 'high',
    category: 'database',
    logs: ['MongoError: Transaction 1 has been aborted', 'WriteConflict error: this operation conflicted with another operation', 'Retrying transaction... attempt 3/3 failed', 'Submission score update rolled back'],
    rootCause: 'Write conflict in multi-document transaction caused by concurrent submission scoring from multiple judge workers',
    suggestedFix: '1. Implement retry logic for transactions with exponential backoff\n2. Reduce transaction scope to minimum operations\n3. Use optimistic concurrency with version fields\n4. Consider using findOneAndUpdate atomic operations instead of transactions',
  },
  {
    title: 'MongoDB Disk Full',
    service: 'judge-service',
    severity: 'critical',
    category: 'database',
    logs: ['WiredTiger error: No space left on device', 'MongoDB disk usage: 99.8%', 'Write operations failing — disk quota exceeded', 'Journal write failed: ENOSPC'],
    rootCause: 'MongoDB WiredTiger journal and data files exhausted available disk space',
    suggestedFix: '1. Immediately free space: remove temp files, old logs\n2. Scale up Atlas cluster storage tier\n3. Enable Atlas auto-scaling for storage\n4. Set up disk usage alerts at 80% threshold\n5. Review and archive old submission documents',
  },

  // === BULLMQ / QUEUE ===
  {
    title: 'BullMQ Worker Crashed',
    service: 'judge-worker',
    severity: 'high',
    category: 'queue',
    logs: ['Worker process exited with code 1', 'BullMQ: Worker lost connection to Redis', 'Unhandled promise rejection in job processor', 'Queue stalled: 47 jobs in waiting state'],
    rootCause: 'Unhandled promise rejection in job processor caused worker process to crash, leaving 47 jobs stalled',
    suggestedFix: '1. Add global uncaught exception handler in worker\n2. Wrap job processor in try-catch\n3. Configure BullMQ stalledInterval to recover stalled jobs\n4. Restart worker: `pm2 restart judge-worker`\n5. Process stalled jobs: call queue.retryJobs()',
  },
  {
    title: 'BullMQ Queue Backlog — Submission Delay',
    service: 'submission-queue',
    severity: 'high',
    category: 'queue',
    logs: ['Queue depth: 2400 jobs', 'Average wait time: 8.5 minutes', 'Worker concurrency at max (10)', 'Jobs completing at 120/min, incoming at 340/min'],
    rootCause: 'Submission burst during contest exceeded worker throughput capacity, queue backlog accumulating',
    suggestedFix: '1. Temporarily scale worker concurrency: increase BULL_CONCURRENCY env var\n2. Add more worker replicas\n3. Rate-limit submission API during peak load\n4. Implement priority queue for contest submissions',
  },
  {
    title: 'BullMQ Job Timeout — TLE in Judge',
    service: 'judge-worker',
    severity: 'medium',
    category: 'queue',
    logs: ['Job timed out after 30000ms', 'Child process killed: SIGKILL', 'JobId: sub_98423 exceeded time limit', 'Docker execution container did not respond'],
    rootCause: 'Infinite loop in user-submitted code caused judge container to hang past job timeout',
    suggestedFix: '1. Verify SIGKILL is sent after timeout (not just SIGTERM)\n2. Add container resource limits: --memory and --cpus flags\n3. Mark job as TLE and return appropriate verdict\n4. This is expected behavior — no action needed if timeout/kill working correctly',
  },
  {
    title: 'BullMQ Redis Connection Lost Mid-Job',
    service: 'email-queue',
    severity: 'medium',
    category: 'queue',
    logs: ['BullMQ: Lost connection to Redis while processing job email:welcome:9823', 'Job lock expired', 'Redis connection dropped: socket hang up', 'Job will be retried on reconnection'],
    rootCause: 'Redis connection dropped mid-job execution causing job lock to expire and triggering retry',
    suggestedFix: '1. Enable BullMQ job idempotency keys to prevent duplicate emails on retry\n2. Increase Redis keepalive settings\n3. Configure maxRetriesPerRequest: null in Redis client\n4. Add job deduplication logic in processor',
  },
  {
    title: 'BullMQ Dead Letter Queue Full',
    service: 'notification-worker',
    severity: 'medium',
    category: 'queue',
    logs: ['Failed jobs in dead letter queue: 892', 'Job notification:push:4521 failed after 3 retries', 'Error: FCM token invalid or expired', 'Bull DLQ size exceeded threshold'],
    rootCause: 'Mass FCM token expiry after app update invalidated push notification tokens, filling dead letter queue',
    suggestedFix: '1. Implement FCM token refresh on 400/404 responses\n2. Remove invalid tokens from database\n3. Clear DLQ after addressing root cause\n4. Add DLQ size alerting',
  },

  // === DOCKER ===
  {
    title: 'Docker Container OOM Kill',
    service: 'judge-sandbox',
    severity: 'high',
    category: 'docker',
    logs: ['Container killed due to OOM (Out of Memory)', 'Killed process 1423 (node) total-vm:512MB, anon-rss:498MB', 'docker: Error response from daemon: OOM killer invoked', 'Container judge-sandbox exited with code 137'],
    rootCause: 'User-submitted code allocated memory beyond container limit (512MB), triggering OOM kill',
    suggestedFix: '1. This is expected for memory-limit-exceeded submissions — return MLE verdict\n2. Ensure exit code 137 is mapped to MLE in judge logic\n3. Verify memory limit flags in docker run command\n4. Log OOM events for monitoring',
  },
  {
    title: 'Docker Image Pull Failure in CI',
    service: 'github-actions',
    severity: 'medium',
    category: 'ci-cd',
    logs: ['Unable to pull image: judge-base:latest', 'Error: pull access denied for registry.example.com/judge-base', 'unauthorized: authentication required', 'docker pull failed with exit code 1'],
    rootCause: 'Docker registry credentials expired in GitHub Actions secrets',
    suggestedFix: '1. Rotate DOCKER_REGISTRY_TOKEN in GitHub Actions secrets\n2. Run: `docker login registry.example.com` and update secret\n3. Check registry token expiry policy\n4. Consider using short-lived tokens via OIDC',
  },
  {
    title: 'Docker Socket Permission Denied',
    service: 'judge-service',
    severity: 'high',
    category: 'docker',
    logs: ['Error: permission denied while trying to connect to the Docker daemon socket', 'dial unix /var/run/docker.sock: connect: permission denied', 'Failed to create execution container'],
    rootCause: 'Service user not in docker group after system update reset group memberships',
    suggestedFix: '1. Add service user to docker group: `usermod -aG docker $USER`\n2. Restart service to apply group change\n3. Verify with: `id $USER`\n4. Consider using rootless Docker for security',
  },
  {
    title: 'Docker Volume Mount Failure',
    service: 'submission-service',
    severity: 'medium',
    category: 'docker',
    logs: ['Error response from daemon: invalid mount config for type "bind"', 'Source path /tmp/submissions/98423 does not exist', 'Container failed to start', 'ENOENT: no such file or directory'],
    rootCause: 'Host path for bind mount was cleaned up by temp file rotation before container could use it',
    suggestedFix: '1. Create temp directory before calling docker run\n2. Add existence check before mount\n3. Use named volumes instead of bind mounts for reliability\n4. Adjust temp file rotation interval',
  },
  {
    title: 'Docker Network Bridge Conflict',
    service: 'infrastructure',
    severity: 'medium',
    category: 'docker',
    logs: ['Error creating network: network with name devsight-net already exists', 'Network bridge IP conflict: 172.18.0.0/16 overlaps with host route', 'Container cannot reach external network', 'Failed to assign IP to container'],
    rootCause: 'Docker network subnet conflicts with existing host network route after VPN connection',
    suggestedFix: '1. Disconnect VPN or change VPN subnet\n2. Delete conflicting Docker network: `docker network rm devsight-net`\n3. Recreate with custom subnet: `--subnet=192.168.100.0/24`\n4. Add custom subnet to docker-compose.yml',
  },

  // === GITHUB ACTIONS / CI-CD ===
  {
    title: 'GitHub Actions Build Failure — TypeScript Error',
    service: 'github-actions',
    severity: 'medium',
    category: 'ci-cd',
    logs: ['tsc: error TS2345: Argument of type \'string\' is not assignable to parameter of type \'number\'', 'src/services/judge.ts(142,18): error TS2339: Property \'exitCode\' does not exist', 'Build failed with 3 TypeScript errors', 'Process exited with code 2'],
    rootCause: 'TypeScript strict mode errors introduced by recent dependency update changed type signatures',
    suggestedFix: '1. Run `npx tsc --noEmit` locally to see all errors\n2. Fix type mismatches in judge.ts lines 142+\n3. Do not suppress with @ts-ignore without understanding the error\n4. Run `npm run build` before pushing',
  },
  {
    title: 'GitHub Actions Test Failure — Integration Tests',
    service: 'github-actions',
    severity: 'medium',
    category: 'ci-cd',
    logs: ['FAIL tests/integration/submission.test.ts', '● Submission flow › should return verdict within 5 seconds', 'Timeout - Async callback was not invoked within 5000ms', 'Jest: Tests failed — 3 failed, 47 passed'],
    rootCause: 'Integration test timeout due to judge worker not running in CI environment',
    suggestedFix: '1. Add judge worker service to GitHub Actions workflow\n2. Or mock judge service in integration tests\n3. Increase Jest timeout for integration tests: `jest.setTimeout(15000)`\n4. Check if REDIS_URL is set in CI environment secrets',
  },
  {
    title: 'GitHub Actions — npm install Fails',
    service: 'github-actions',
    severity: 'low',
    category: 'ci-cd',
    logs: ['npm ERR! code ERESOLVE', 'npm ERR! ERESOLVE unable to resolve dependency tree', 'npm ERR! peer dep missing: react@^17.0.0, required by some-package@1.2.0', 'npm install failed with exit code 1'],
    rootCause: 'Peer dependency conflict after upgrading React from 17 to 18',
    suggestedFix: '1. Run `npm install --legacy-peer-deps` as workaround\n2. Or upgrade conflicting package to React 18 compatible version\n3. Check package changelog for React 18 support\n4. Pin dependency versions in package.json',
  },
  {
    title: 'GitHub Actions Deployment Failed — Health Check Timeout',
    service: 'github-actions',
    severity: 'high',
    category: 'ci-cd',
    logs: ['Deploying to production...', 'Waiting for health check at /health', 'Health check attempt 1/10: FAILED (connection refused)', 'Health check attempt 10/10: FAILED', 'Deployment failed — rollback initiated'],
    rootCause: 'New build failed to start due to missing environment variable introduced in this release',
    suggestedFix: '1. Check deployment logs on server: `pm2 logs api`\n2. Verify all required env vars are set in production\n3. Check for startup errors in application logs\n4. If rollback occurred, deployment is safe — fix env var and redeploy',
  },
  {
    title: 'GitHub Actions — Docker Build Cache Miss',
    service: 'github-actions',
    severity: 'low',
    category: 'ci-cd',
    logs: ['Cache miss for key: docker-buildx-node-deps', 'Rebuilding all layers from scratch', 'Step 5/12: RUN npm install (1847 packages)', 'Build time: 8m 42s (expected ~2m with cache)'],
    rootCause: 'Package.json changed causing Docker layer cache invalidation for npm install step',
    suggestedFix: '1. This is expected behavior — cache will be warm on next run\n2. If frequent: separate COPY package.json from COPY source\n3. Use docker/build-push-action with cache-from/cache-to\n4. Consider GitHub Actions cache for node_modules',
  },

  // === SOCKET.IO / REALTIME ===
  {
    title: 'Socket.IO Mass Disconnect Event',
    service: 'realtime-service',
    severity: 'high',
    category: 'realtime',
    logs: ['[socket.io] 847 clients disconnected simultaneously', 'Error: Transport close', 'WebSocket connection failed: 1006', 'Reconnection storm: 847 clients attempting reconnect'],
    rootCause: 'Node.js process restart during deployment caused mass WebSocket disconnection and reconnection storm',
    suggestedFix: '1. Implement graceful shutdown: drain connections before restart\n2. Use sticky sessions if behind load balancer\n3. Add exponential backoff for client reconnection\n4. Use Redis adapter to maintain room state across restarts',
  },
  {
    title: 'Socket.IO Room Sync Failure',
    service: 'collaboration-service',
    severity: 'medium',
    category: 'realtime',
    logs: ['Room state out of sync for room: contest-123', 'Client A received event, Client B did not', 'Redis adapter publish failed', 'Socket.IO namespace /collaborate: event delivery unconfirmed'],
    rootCause: 'Redis adapter connection dropped causing socket.io events to not broadcast across server instances',
    suggestedFix: '1. Check Redis adapter connection: verify REDIS_URL for socket.io adapter\n2. Enable socket.io connection state recovery\n3. Add acknowledgement callbacks for critical events\n4. Implement client-side state reconciliation on reconnect',
  },
  {
    title: 'Socket.IO Memory Leak — Event Listeners',
    service: 'realtime-service',
    severity: 'medium',
    category: 'realtime',
    logs: ['MaxListenersExceededWarning: Possible EventEmitter memory leak detected', 'Added more than 11 listeners for event \'disconnect\'', 'Heap memory growing: 512MB → 1.8GB over 6 hours', 'Process restarted by PM2 due to memory limit'],
    rootCause: 'Socket event listeners not removed on disconnect, accumulating across reconnections',
    suggestedFix: '1. Use `socket.once()` instead of `socket.on()` for one-time handlers\n2. Call `socket.removeAllListeners()` in disconnect handler\n3. Use `socket.offAny()` to clean up catch-all listeners\n4. Add memory monitoring with PM2 or clinic.js',
  },

  // === API ===
  {
    title: 'API 500 — Unhandled Promise Rejection',
    service: 'api-gateway',
    severity: 'high',
    category: 'api',
    logs: ['UnhandledPromiseRejectionWarning: MongooseError: Query was already executed', 'at router.post (/app/routes/submissions.js:87:12)', 'HTTP 500 Internal Server Error', 'User-facing error on /api/submit'],
    rootCause: 'Mongoose query executed twice due to missing await causing double-execution of query callback',
    suggestedFix: '1. Add missing await before Mongoose query\n2. Add global unhandledRejection handler for better error messages\n3. Never call .exec() and await simultaneously\n4. Run in strict mode to catch these earlier',
  },
  {
    title: 'API Rate Limit Exceeded — External Service',
    service: 'email-service',
    severity: 'medium',
    category: 'api',
    logs: ['SendGrid API error: 429 Too Many Requests', 'Rate limit: 100 emails/second exceeded', 'Retry-After: 60 seconds', 'Email queue backing up: 340 pending'],
    rootCause: 'Contest end triggered bulk result emails exceeding SendGrid rate limit',
    suggestedFix: '1. Implement email sending rate limiting: max 80 emails/sec\n2. Use BullMQ with rate limiting: rateLimiter config\n3. Batch emails where possible\n4. Upgrade SendGrid plan if regular occurrence',
  },
  {
    title: 'API JWT Verification Failed',
    service: 'auth-service',
    severity: 'medium',
    category: 'api',
    logs: ['JsonWebTokenError: invalid signature', 'JWT verification failed for user request', 'HTTP 401 Unauthorized', 'JWT_SECRET mismatch between instances'],
    rootCause: 'JWT_SECRET env var differs between service instances after rolling deployment',
    suggestedFix: '1. Ensure JWT_SECRET is identical across all instances\n2. Store JWT_SECRET in secrets manager (AWS SSM, Vault)\n3. Do not rotate JWT_SECRET without invalidating all tokens\n4. Consider using RS256 (asymmetric) to avoid secret sharing',
  },
  {
    title: 'API Timeout — Slow Database Query',
    service: 'leaderboard-service',
    severity: 'medium',
    category: 'api',
    logs: ['Request timeout after 30000ms', 'Mongoose: query exceeded 25000ms', 'GET /api/leaderboard?contestId=456 504', 'Collection scan on submissions: 2.4M documents'],
    rootCause: 'Full collection scan on submissions due to missing compound index on (contestId, score)',
    suggestedFix: '1. Add compound index: `db.submissions.createIndex({ contestId: 1, score: -1 })`\n2. Add to Mongoose schema definition\n3. Test query performance with `.explain("executionStats")`\n4. Cache leaderboard results in Redis with 30s TTL',
  },
  {
    title: 'API CORS Error — Frontend Blocked',
    service: 'api-gateway',
    severity: 'low',
    category: 'api',
    logs: ['Access to XMLHttpRequest blocked by CORS policy', 'Response to preflight has invalid HTTP status code 404', 'Missing CORS headers on /api/problems', 'Frontend fetch failed for origin: https://app.coderome.io'],
  rootCause: 'New production domain not added to CORS allowlist in API gateway config',
    suggestedFix: '1. Add production domain to CORS origin array\n2. Redeploy API gateway\n3. Verify preflight OPTIONS requests return 200\n4. Add CLIENT_URL env var for new domain',
  },

  // === INFRASTRUCTURE ===
  {
    title: 'Node.js Heap Out of Memory',
    service: 'submission-service',
    severity: 'critical',
    category: 'api',
    logs: ['FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory', 'Fatal javascript OOM in heap allocation', 'Aborted (core dumped)', 'Process crashed: submission-service'],
    rootCause: 'Memory leak in submission service causing heap to grow unchecked during high submission load',
    suggestedFix: '1. Restart service immediately: `pm2 restart submission-service`\n2. Set Node.js heap size: `node --max-old-space-size=4096`\n3. Profile memory with `--inspect` flag and Chrome DevTools\n4. Look for circular references or unclosed streams',
  },
  {
    title: 'PM2 Process Restart Loop',
    service: 'api-gateway',
    severity: 'high',
    category: 'api',
    logs: ['PM2: app api-gateway restarted (15 times in last hour)', 'App crashed — waiting 5 seconds before restart', 'Error: listen EADDRINUSE: address already in use :::4000', 'Failed to bind to port 4000'],
    rootCause: 'Previous process not fully exited before PM2 restart, causing port 4000 to remain in use',
    suggestedFix: '1. Kill lingering process: `lsof -ti:4000 | xargs kill -9`\n2. Increase PM2 kill timeout: `kill_timeout: 5000`\n3. Add graceful shutdown handler for SIGTERM\n4. Check PM2 ecosystem.config.js for restart limits',
  },
  {
    title: 'SSL Certificate Expired',
    service: 'infrastructure',
    severity: 'critical',
    category: 'api',
    logs: ['SSL_ERROR_RX_RECORD_TOO_LONG', 'Certificate expired: notAfter=Jan 15 2026', 'curl: (60) SSL certificate problem: certificate has expired', 'HTTPS requests failing for all users'],
    rootCause: 'Let\'s Encrypt certificate auto-renewal failed due to DNS misconfiguration',
    suggestedFix: '1. Immediate: renew manually `certbot renew --force-renewal`\n2. Fix DNS challenge: verify DNS records\n3. Test auto-renewal: `certbot renew --dry-run`\n4. Set up monitoring for cert expiry 30 days before',
  },
  {
    title: 'Disk Space Alert — Log Files',
    service: 'infrastructure',
    severity: 'medium',
    category: 'api',
    logs: ['df: /var/log: 94% disk used', 'PM2 log rotation failed: No space left on device', 'Nginx error log: 18GB', 'Application logs growing at 2GB/day'],
    rootCause: 'Log rotation not configured, PM2 and Nginx logs grew unbounded',
    suggestedFix: '1. Clear old logs: `pm2 flush` and `truncate -s 0 /var/log/nginx/error.log`\n2. Configure logrotate for all services\n3. Set PM2 log rotation: `pm2 install pm2-logrotate`\n4. Set max log size in logrotate config',
  },

  // === JUDGE SERVICE ===
  {
    title: 'Judge Service — Execution Container Startup Failure',
    service: 'judge-service',
    severity: 'high',
    category: 'docker',
    logs: ['Failed to create execution container for submission sub_7823', 'docker: Error response from daemon: cannot allocate memory in static TLS block', 'Container failed to start after 3 attempts', 'Judge verdict: SYSTEM_ERROR'],
    rootCause: 'System running out of memory for container allocation under high concurrent submission load',
    suggestedFix: '1. Limit concurrent executions: reduce JUDGE_CONCURRENCY env var\n2. Add memory limits to judge containers\n3. Scale up server RAM or add judge workers\n4. Queue overflow submissions rather than failing immediately',
  },
  {
    title: 'Judge Service — Verdict Mismatch',
    service: 'judge-service',
    severity: 'medium',
    category: 'api',
    logs: ['Expected: AC, Got: WA for problem prob_123', 'Test case output mismatch on case 7/10', 'Whitespace difference detected in output comparison', 'Strict comparison mode: trailing newlines differ'],
    rootCause: 'Output comparison not trimming trailing whitespace, causing Wrong Answer on valid solutions',
    suggestedFix: '1. Trim output before comparison: `output.trim() === expected.trim()`\n2. Update judge comparison logic\n3. Re-evaluate affected submissions\n4. Document comparison policy for problem setters',
  },
  {
    title: 'Judge Service — Language Runtime Missing',
    service: 'judge-service',
    severity: 'high',
    category: 'docker',
    logs: ['exec: "rustc": executable file not found in $PATH', 'Language runtime not found: rust', 'Submission sub_9234 failed: COMPILATION_ERROR', 'Docker image judge-base:latest missing Rust runtime'],
    rootCause: 'Rust runtime not included in judge base image after recent image rebuild',
    suggestedFix: '1. Add Rust to judge Dockerfile: `RUN curl --proto \'=https\' --tlsv1.2 -sSf https://sh.rustup.rs | sh`\n2. Rebuild and push judge-base image\n3. Update CI to verify all supported languages\n4. Add language availability test to deployment checks',
  },

  // === WEBSOCKET / CONTEST ===
  {
    title: 'Contest Service — Leaderboard Stale',
    service: 'contest-service',
    severity: 'low',
    category: 'realtime',
    logs: ['Leaderboard cache stale by 45 seconds', 'Redis cache miss for key: leaderboard:contest:789', 'Cache invalidation event not received', 'Users seeing outdated scores during contest'],
    rootCause: 'Redis pub/sub cache invalidation message lost due to network blip during contest',
    suggestedFix: '1. Add TTL-based fallback: recompute if cache older than 30s\n2. Use Redis Streams instead of pub/sub for durability\n3. Implement polling fallback for leaderboard updates\n4. Add cache freshness timestamp to API response',
  },
  {
    title: 'Contest Submission Flood — API Throttled',
    service: 'api-gateway',
    severity: 'high',
    category: 'api',
    logs: ['Rate limiter triggered: 50 req/min exceeded for user u_4521', 'HTTP 429 Too Many Requests', 'IP 192.168.1.45 blocked for 60 seconds', 'Automated submission script detected'],
    rootCause: 'User running automated script flooding submission endpoint during live contest',
    suggestedFix: '1. Rate limiting is working correctly — this is expected behavior\n2. Review user account for ToS violation\n3. Consider per-problem submission cooldown (30s)\n4. Add CAPTCHA for submission endpoint if abuse continues',
  },

  // === AUTH ===
  {
    title: 'Auth Service — OAuth Callback Failure',
    service: 'auth-service',
    severity: 'medium',
    category: 'api',
    logs: ['OAuth callback: state mismatch', 'GitHub OAuth error: redirect_uri_mismatch', 'Error: The redirect_uri does not match', 'OAuth login failing for all GitHub users'],
    rootCause: 'Production OAuth redirect URI not registered in GitHub OAuth App settings after domain change',
    suggestedFix: '1. Add new domain to GitHub OAuth App callback URLs\n2. Go to GitHub → Settings → Developer settings → OAuth Apps\n3. Add: https://newdomain.com/auth/github/callback\n4. Update OAUTH_REDIRECT_URI env var',
  },
  {
    title: 'Auth Service — Refresh Token Invalidated',
    service: 'auth-service',
    severity: 'medium',
    category: 'api',
    logs: ['JWT refresh token validation failed', 'Token blacklisted or revoked', 'All users logged out simultaneously', 'REFRESH_TOKEN_SECRET rotation detected'],
    rootCause: 'REFRESH_TOKEN_SECRET env var changed during deployment, invalidating all existing refresh tokens',
    suggestedFix: '1. Do not change REFRESH_TOKEN_SECRET in production without a migration plan\n2. Implement token versioning to gracefully invalidate old tokens\n3. Users must re-login — communicate via status page\n4. Use key rotation strategy with overlap period next time',
  },

  // === DATABASE MIGRATION ===
  {
    title: 'MongoDB Migration Failed — Schema Change',
    service: 'migration-service',
    severity: 'high',
    category: 'database',
    logs: ['Migration 007_add_submission_metadata failed', 'MongoServerError: Document failed validation', 'Existing documents missing required field: submissionType', 'Migration rolled back'],
    rootCause: 'Migration added required field without default value, failing validation for existing documents',
    suggestedFix: '1. Add default value to migration: use $set with $ifNull\n2. Two-step migration: add optional field, backfill, then make required\n3. Test migrations against production data snapshot\n4. Use mongo-migrate with dry-run mode before applying',
  },

  // === NETWORK ===
  {
    title: 'DNS Resolution Failure',
    service: 'api-gateway',
    severity: 'high',
    category: 'api',
    logs: ['Error: getaddrinfo ENOTFOUND mongodb.internal', 'DNS lookup failed for service: redis.internal', 'Service discovery failing for internal hostnames', 'All inter-service calls failing'],
    rootCause: 'Internal DNS server unreachable after network configuration change in infrastructure',
    suggestedFix: '1. Check DNS server status: `dig @8.8.8.8 mongodb.internal`\n2. Temporarily use IP addresses in connection strings\n3. Check /etc/resolv.conf points to correct nameserver\n4. Restart Docker network if using Docker DNS',
  },
  {
    title: 'Load Balancer Health Check Failing',
    service: 'infrastructure',
    severity: 'high',
    category: 'api',
    logs: ['Health check failed: GET /health returned 502', 'Backend instance i-0abc123 marked unhealthy', 'Only 1/3 instances passing health checks', 'Increased latency: p99 latency 4200ms'],
    rootCause: 'Two of three API instances crashed due to memory exhaustion, load concentrating on single instance',
    suggestedFix: '1. Restart crashed instances\n2. Check memory usage on all instances\n3. Investigate root cause of memory exhaustion\n4. Set up auto-scaling to add instances when CPU/memory threshold crossed',
  },
];
